openapi: 3.0.1
info:
  title: MedIQ API
  version: 'v1'
paths:
  /accounts:
    get:
      summary: List all accounts
      tags:
        - Accounts
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    first_name:
                      type: string
                    last_name:
                      type: string
                    email:
                      type: string
